[package]
name = "bdk_transaction"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
homepage = "https://bitcoindevkit.org"
repository = "https://github.com/bitcoindevkit/bdk-tx"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
bitcoin = { version = "0.32" }
miniscript = { version = "12" }

[dev-dependencies]
anyhow = "1"
bdk_coin_select = "0.3"

[dev-dependencies.bdk_wallet]
path = "../bdk/crates/wallet"
#git = "https://github.com/ValuedMammal/bdk"
#branch = "feat/bdk-tx-provider"
features = ["rusqlite", "test-utils"]


[[example]]
name = "wallet"
