[package]
name = "bdk_transaction"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
homepage = "https://bitcoindevkit.org"
repository = "https://github.com/bitcoindevkit/bdk-tx"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
miniscript = { version = "12", default-features = false }

[dev-dependencies]
anyhow = "1"
bdk_chain = { version = "0.21" }
bdk_coin_select = { version = "0.3" }

[features]
default = ["std"]
std = ["miniscript/std"]
